export const SECTION_KEYS = {
  TEXT_FIELD: 'TEXT_FIELD',
  TEXT_AND_FILE: 'TEXT_AND_FILE',
  DESCRIPTION: 'DESCRIPTION',
  REVIEW_AND_PLACE: 'REVIEW_AND_PLACE',
  MULTI_SELECT_AND_TEXT: 'MULTI_SELECT_AND_TEXT',
  DESCRIPTION_AND_FILE: 'DESCRIPTION_AND_FILE',
} as const

export type SectionKey = (typeof SECTION_KEYS)[keyof typeof SECTION_KEYS]

export const REVIEW_AND_PLACE = SECTION_KEYS.REVIEW_AND_PLACE
